### ISSUE TITLE
Task Review 1.3.40

### ISSUE THREAD

**Issue by vkusneishiyMohenTohen** [Azro08/java-tasks#3]
https://github.com/Azro08/java-tasks/blob/1da02856368abcf9ee2dabc1c4c3979eb5f85c6b/third-task-1.3/src/main/java/movetofront/LinkedList.java#L21

Для чего здесь нужен метод reverse()

**Comment by Azro08** [comment]
чтобы развернуть связный список

**Comment by vkusneishiyMohenTohen** [comment]
![image](https://user-images.githubusercontent.com/127477604/224701199-b8ad4b35-17ee-4631-9f26-8293a9ad9b98.png)
 Из-за использования метода reverse нарушается последовательность элементов, думая он тут вообще не нужен.

**Comment by Azro08** [comment]
В условии задачи как я понял при вводе символа его надо вставить в начало списка а не в конец поэтому я развернул список и удалил повторяющееся символы.

**Comment by vkusneishiyMohenTohen** [comment]
Все верно: все элементы вставляются в начало списка. А когда встречается повторяющийся символ, тот, что уже где-то в списке, удаляется, а этот вставляется в начало. Порядок списка никак не меняется при этом, поэтому метод reverse() здесь избыточен

**Comment by Azro08** [comment]
Ошибка исправлена

**Comment by vkusneishiyMohenTohen** [comment]
Засчитано.
